<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<title>libsigc++: Member List</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<link href="doxygen.css" rel="stylesheet" type="text/css"/>
</head>
<body>
<!-- Generated by Doxygen 1.6.1 -->
<div class="navigation" id="top">
  <div class="tabs">
    <ul>
      <li><a href="index.html"><span>Main&#160;Page</span></a></li>
      <li><a href="modules.html"><span>Modules</span></a></li>
      <li><a href="namespaces.html"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.html"><span>Classes</span></a></li>
    </ul>
  </div>
  <div class="tabs">
    <ul>
      <li><a href="annotated.html"><span>Class&#160;List</span></a></li>
      <li><a href="classes.html"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.html"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.html"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
</div>
<div class="contents">
<h1>sigc::hide_functor&lt; 5, T_functor &gt; Member List</h1>This is the complete list of members for <a class="el" href="structsigc_1_1hide__functor_3_015_00_01T__functor_01_4.html">sigc::hide_functor&lt; 5, T_functor &gt;</a>, including all inherited members.<table>
  <tr bgcolor="#f0f0f0"><td><b>adaptor_type</b> typedef (defined in <a class="el" href="structsigc_1_1hide__functor_3_015_00_01T__functor_01_4.html">sigc::hide_functor&lt; 5, T_functor &gt;</a>)</td><td><a class="el" href="structsigc_1_1hide__functor_3_015_00_01T__functor_01_4.html">sigc::hide_functor&lt; 5, T_functor &gt;</a></td><td></td></tr>
  <tr class="memlist"><td><a class="el" href="structsigc_1_1adapts.html#a947b69ccbdcabd4ef4163dcab96096f8">adapts</a>(const T_functor&amp; _A_functor)</td><td><a class="el" href="structsigc_1_1adapts.html">sigc::adapts&lt; T_functor &gt;</a></td><td><code> [inline, explicit]</code></td></tr>
  <tr class="memlist"><td><a class="el" href="structsigc_1_1adapts.html#a2f4b37eb160708baf17de57f2abce7a7">functor_</a></td><td><a class="el" href="structsigc_1_1adapts.html">sigc::adapts&lt; T_functor &gt;</a></td><td><code> [mutable]</code></td></tr>
  <tr class="memlist"><td><a class="el" href="structsigc_1_1hide__functor_3_015_00_01T__functor_01_4.html#a55264516f83ff42acdbb26b5054586f3">hide_functor</a>(const T_functor&amp; _A_func)</td><td><a class="el" href="structsigc_1_1hide__functor_3_015_00_01T__functor_01_4.html">sigc::hide_functor&lt; 5, T_functor &gt;</a></td><td><code> [inline, explicit]</code></td></tr>
  <tr class="memlist"><td><a class="el" href="structsigc_1_1hide__functor_3_015_00_01T__functor_01_4.html#a38703790d9acc4753c18fa3f86c25686">operator()</a>(T_arg1 _A_a1, T_arg2 _A_a2, T_arg3 _A_a3, T_arg4 _A_a4, T_arg5 _A_a5, T_arg6)</td><td><a class="el" href="structsigc_1_1hide__functor_3_015_00_01T__functor_01_4.html">sigc::hide_functor&lt; 5, T_functor &gt;</a></td><td><code> [inline]</code></td></tr>
  <tr class="memlist"><td><a class="el" href="structsigc_1_1hide__functor_3_015_00_01T__functor_01_4.html#a7ed003b3945502ae4d73bab028d313c4">operator()</a>(T_arg1 _A_a1, T_arg2 _A_a2, T_arg3 _A_a3, T_arg4 _A_a4, T_arg5 _A_a5, T_arg6, T_arg7 _A_a7)</td><td><a class="el" href="structsigc_1_1hide__functor_3_015_00_01T__functor_01_4.html">sigc::hide_functor&lt; 5, T_functor &gt;</a></td><td><code> [inline]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td><b>result_type</b> typedef (defined in <a class="el" href="structsigc_1_1hide__functor_3_015_00_01T__functor_01_4.html">sigc::hide_functor&lt; 5, T_functor &gt;</a>)</td><td><a class="el" href="structsigc_1_1hide__functor_3_015_00_01T__functor_01_4.html">sigc::hide_functor&lt; 5, T_functor &gt;</a></td><td></td></tr>
</table></div>
<hr size="1"/><address style="text-align: right;"><small>Generated on Fri Jun 4 16:11:47 2010 for libsigc++ by&#160;
<a href="http://www.doxygen.org/index.html">
<img class="footer" src="doxygen.png" alt="doxygen"/></a> 1.6.1 </small></address>
</body>
</html>
